[build]
  command = "npm install --force && npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://rayappan.pythonanywhere.com"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"

[[redirects]]
  from = "/api/*"
  to = "http://13.60.98.6:5001/api/:splat"
  status = 200